
services:
  # This is just a dummy service, as docker compose requires at least 
  # one service to be defined in the root compose.yml file.
  # 
  # The following compose files contain additional services:
  # 
  # Required
  #   - compose.apicurio.yml
  #   - compose.grafana.yml
  #   - compose.kafka.cluster.yml --- OR --- compose.kafka.single.yml
  #   - compose.microsoft-sql-server.yml
  #   - compose.opentelemetry.yml
  #   - compose.postgresql.yml
  #   - compose.valkey.yml
  #
  # You can adjust which compose files are loaded by modifying the `COMPOSE_FILE` 
  # and `COMPOSE_PROFILES` environment variables in the `.env` file.
  #
  dummy:
    image: busybox@sha256:fd7dc98638c8e305f4dc34e979f1c0fdfdcaeb0fbf8fcff77ae834b6da3d7e6e
    command: ["sh", "-c", "tail -f /dev/null"]
    profiles: ["dummy"] 

networks:
  default:
    driver: bridge
