name: rune-vikestad

services:
  microsoft-sql-server-2022:
    container_name: microsoft-sql-server-2022
    hostname: microsoft-sql-server-2022
    restart: unless-stopped
    build:
      context: ./microsoft-sql-server-2022
      dockerfile: Dockerfile
    profiles:
      - microsoft-sql-server-2022
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: BiMZmVQdNff4ki3X
      MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS
      MSSQL_PID: Developer
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4G
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S 127.0.0.1,1433 -U sa -P \"$${MSSQL_SA_PASSWORD}\" -Q \"SELECT 1\" > /dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s
    ports:
      - "1433:1433"
    volumes:
      - microsoft-sql-server-2022-data:/var/opt/mssql
    networks:
      - default

volumes:
  microsoft-sql-server-2022-data:
    external: false

networks:
  default:
    driver: bridge
    external: false
