receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 512
    timeout: 5s
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 100

exporters:
  # Grafana Loki
  otlphttp/loki:
    endpoint: http://grafana-loki:3100/otlp
  # Grafana Mimir
  otlphttp/mimir:
    endpoint: http://grafana-mimir:9009/otlp
  # Grafana Tempo
  otlp/tempo:
    endpoint: grafana-tempo:4317
    tls:
      insecure: true
  # Open Telemetry Satellite Service (e.g. JetBrains Rider)
  otlp/rider:
    endpoint: localhost:17011
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: /health/status
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, zpages]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/loki, otlp/satellite]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/mimir, otlp/satellite]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo, otlp/satellite]
  telemetry:
    logs:
      level: error
