apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    url: http://grafana-loki:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: "tempo"
          matcherRegex: "trace_id"
          matcherType: "label"
          name: "trace_id"
          url: "$${__value.raw}"
  - name: Mimir
    type: prometheus
    uid: mimir
    url: http://grafana-mimir:9009/prometheus
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
      prometheusType: Mimir
      prometheusVersion: 2.9.1
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://grafana-tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      search:
        filters:
          - id: service-name
            operator: =
            scope: resource
            tag: service.name
          - id: span-name
            operator: =
            scope: span
            tag: name
      serviceMap:
        datasourceUid: mimir
      tracesToLogsV2:
        customQuery: true
        datasourceUid: loki
        filterByTraceID: false
        query: '{$${__tags}} | trace_id="$${__trace.traceId}"'
        spanEndTimeShift: 30s
        spanStartTimeShift: -30s
        tags:
          - key: service.name
            value: service_name
